# Generated by Django 5.1.4 on 2025-01-25 23:47

import django.db.models.deletion
import django.utils.timezone
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('recollection', markdownx.models.MarkdownxField()),
                ('preoccupation', models.TextField(blank=True)),
                ('interpretation', markdownx.models.MarkdownxField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='symbols')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbolism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreams.dream', verbose_name='dream')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreams.symbol', verbose_name='symbol')),
            ],
        ),
        migrations.AddField(
            model_name='dream',
            name='symbols',
            field=models.ManyToManyField(blank=True, related_name='dreams', through='dreams.Symbolism', to='dreams.symbol'),
        ),
    ]
