# Generated by Django 5.1.4 on 2025-01-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0002_case_insensitive_collation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='name',
            field=models.CharField(db_collation='case_insensitive', max_length=255, unique=True, verbose_name='symbols'),
        ),
    ]
